mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mythril/interfaces/cli.py", line 975, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.10/site-packages/mythril/interfaces/cli.py", line 726, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/usr/local/lib/python3.10/site-packages/mythril/mythril/mythril_disassembler.py", line 277, in load_from_solidity
    solc_binary, self.solc_version = util.extract_binary(file)
  File "/usr/local/lib/python3.10/site-packages/mythril/ethereum/util.py", line 225, in extract_binary
    version = extract_version(file_data)
  File "/usr/local/lib/python3.10/site-packages/mythril/ethereum/util.py", line 194, in extract_version
    pragma_dict = parse_pragma(version_line)
  File "/usr/local/lib/python3.10/site-packages/mythril/ethereum/util.py", line 158, in parse_pragma
    result = pragma.parseString(solidity_code)
  File "/usr/local/lib/python3.10/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.10/site-packages/pyparsing.py", line 3342, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected Re:('\\s*[0-9]+\\s*\\.\\s*[0-9]+\\s*(\\.\\s*[0-9]+)?'), found '\'  (at char 16), (line:1, col:17)

